server:
  port: 8080
  servlet:
    context-path: /ems-thymeleaf

spring:
  thymeleaf:
    cache:false
    prefix:classpath:/templates/
    suffix:.html

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems?characterEncoding=UTF-8
    username: root
    password: root


mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*.xml
  type-aliases-package: cn.lockroot.loop.thymeledemo.entity

logging:
  level:
    root: info
    cn:lockroot:loop:thymeledemo: debug




